import test from 'node:test';import assert from 'node:assert/strict';import {evaluateEnvelope,retryDecision,releaseDecision,localCompletion,compatibility} from '../lib/operations-release-protocols.mjs';
test('joint envelope cannot average away a hard floor',()=>assert.equal(evaluateEnvelope({quality:1,queue:4},{floors:[{key:'quality',min:2}],ceilings:[{key:'queue',max:5}],degradedMode:'proposal-only'}).mode,'proposal-only'));
test('unknown effect reconciles instead of retrying',()=>assert.equal(retryDecision({attempts:0,maxAttempts:3,effectState:'unknown',deadlineLive:true}),'reconcile'));
test('expired retry stops',()=>assert.equal(retryDecision({attempts:0,maxAttempts:3,effectState:'none',deadlineLive:false}),'stop'));
test('release requires reachable stop owner',()=>assert.equal(releaseDecision({question:'q',control:'c',stopOwnerReachable:false,exitGate:'g',effectCeiling:0}),'hold'));
test('bounded release passes complete gate',()=>assert.equal(releaseDecision({question:'q',control:'c',stopOwnerReachable:true,exitGate:'g',effectCeiling:0}),'bounded-exposure'));
test('remote completion is insufficient with wrong tenant',()=>assert.equal(localCompletion({terminal:true},{schema:'v1',tenant:'south',fresh:true,effect:'none'},{schema:'v1',tenant:'north'}),false));
test('valid remote artifact can satisfy local read-only contract',()=>assert.equal(localCompletion({terminal:true},{schema:'v1',tenant:'north',fresh:true,effect:'none'},{schema:'v1',tenant:'north'}),true));
test('effect drift quarantines adapter',()=>assert.equal(compatibility({identity:'r',schema:'v1',effect:'read'},{identity:'r',schema:'v1',effect:'write'}),'quarantined-pending-review'));
test('identity drift is incompatible',()=>assert.equal(compatibility({identity:'r',schema:'v1',effect:'read'},{identity:'x',schema:'v1',effect:'read'}),'incompatible'));
